### ISSUE TITLE
No attribute with the name adg exists when kgf.adaptive_grain()

### ISSUE THREAD

**Issue by and101** [Irrational-Encoding-Wizardry/kagefunc#12]
As per title, when I try to use the adaptive_grain function, I am getting the following error:

Failed to evaluate the script:
Python exception: No attribute with the name adg exists. Did you mistype a plugin namespace?

Am I missing a DLL?

**Comment by LightArrowsEXE** [comment]
Yes; you can find it [here](https://git.kageru.moe/kageru/adaptivegrain).

**Comment by and101** [comment]
Brilliant, totally missed that. Thanks
