### ISSUE TITLE
Cant build on aur

### ISSUE THREAD

**Issue by Motophan** [Irrational-Encoding-Wizardry/kagefunc#13]
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
  CXX      ../../src/AvstpWrapper.lo
  CXX      ../../src/main.lo
In file included from ../fmtconv/build/unix/../../src/fmtc/Bitdepth.h:36,
                 from ../fmtconv/build/unix/../../src/main.cpp:18:
../fmtconv/build/unix/../../src/vsutl/FilterBase.h:30:10: fatal error: VapourSynth.h: No such file or directory
   30 | #include "VapourSynth.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1214: ../../src/main.lo] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
checking dependencies...

**Comment by kageru** [comment]
That’s not an issue with kagefunc but with fmtconf, and judging by the error message, you don’t have vapoursynth installed, or the compiler can’t find the include which makes fmtc fail.
Not my bug, and probably not fmtc’s bug either. Try reinstalling Vapoursynth.

**Comment by Motophan** [comment]
Hey sorry about not self-closing this, this was actually caused by me not having base devl.

You helped me in discord. is it possible to add a sanity check for base devl or is that like something that's so ingrained that only people who have never used arch before would have an issue with.

**Comment by kageru** [comment]
No. `base-devel` is considered an implicit dependency of all AUR packages (https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started), so adding a check to every single package is just a lot of unnecessary work.

**Comment by Motophan** [comment]
Thank you for your kind words. I understand now
