### ISSUE TITLE
Question regarding adpative grain

### ISSUE THREAD

**Issue by Selur** [Irrational-Encoding-Wizardry/kagefunc#16]
what's the 
```
if get_depth(clip) != 8:
        mask = depth(mask, get_depth(clip))
```
actually doing.
get_depth returns the depth of the input clip
but what does depth do?
Shouldn't mask already be the same bit depth as clip and grained?

**Comment by LightArrowsEXE** [comment]
I believe that at some point, `adg` couldn't handle specific bitdepths properly and would always return a GRAY8 clip. It's likely an oversight from back then. I've just checked as well and it returns GRAY16/GrayS clips as you would expect so yeah, they should already be the same.

**Comment by Selur** [comment]
Thanks :)

**Comment by kageru** [comment]
Check removed in a1e89b1 (#17)
