### ISSUE TITLE
No attribute with the name "knlm" exists. Did you mistype a plugin namespace?!

### ISSUE THREAD

**Issue by unixfx** [Irrational-Encoding-Wizardry/kagefunc#2]
Hi.
First thank you for the great work.
ActuallyI got an error, the problem is with this word "knlm"

This is the code 

```
 `from vapoursynth import core
import vapoursynth as vs
core = vs.get_core()
import fvsfunc as fvf
import mvsfunc as mvf
import kagefunc as kgf
import havsfunc as hvf
import fag3kdb as fag3kdb
import sharpaamcmod as sharpaamcmod
 

src   =  core.lsmas.LWLibavSource("DC.mkv")
out   = sharpaamcmod.sharpaamcmod(src, dark=20, thin=0, sharp=15, smooth=0.2, stabilize=False)
out   = kgf.hybriddenoise(out, knl=2, sigma = 2, radius1=2)  
ref    = out
out   = out.f3kdb.Deband(range = 15, output_depth=16)
mask = kgf.retinex_edgemask(ref).std.Inflate()
merged  = core.std.MaskedMerge(out, ref, mask)
merged  = kgf.adaptive_grain(merged, 0.2)
merged  = mvf.Depth(merged, 10)
ff  = merged.std.Trim(3855,3860)
ff.set_output()`
```

**the error** 

> 
> `Failed to evaluate the script:
> Python exception: No attribute with the name knlm exists. Did you mistype a plugin namespace?
> 
> Traceback (most recent call last):
> File "src\cython\vapoursynth.pyx", line 1810, in vapoursynth.vpy_evaluateScript (src\cython\vapoursynth.c:36455)
> File "C:/Users/--/Desktop/ep 75/DC_loslss.vpy", line 19, in 
> out = kgf.hybriddenoise(out, knl=2, sigma = 2, radius1=2)
> File "C:\Users\--\AppData\Local\Programs\Python\Python36\lib\site-packages\kagefunc.py", line 383, in hybriddenoise
> """
> File "C:\Users\--\AppData\Local\Programs\Python\Python36\lib\site-packages\kagefunc.py", line 383, in 
> """
> File "src\cython\vapoursynth.pyx", line 1524, in vapoursynth._CoreProxy.__getattr__ (src\cython\vapoursynth.c:31934)
> File "src\cython\vapoursynth.pyx", line 1379, in vapoursynth.Core.__getattr__ (src\cython\vapoursynth.c:29142)
> AttributeError: No attribute with the name knlm exists. Did you mistype a plugin namespace?`

**Comment by BluBb-mADe** [comment]
You are probably just missing the plugin knlm. https://github.com/Khanattila/KNLMeansCL
You either have to provide the `use_gpu=False` argument or install knlm.
