### ISSUE TITLE
retinex_edgemask enhancement (maybe?)

### ISSUE THREAD

**Issue by nobananasforyou** [Irrational-Encoding-Wizardry/kagefunc#21]
Hello.

I was wondering if there is a possibility of adding an intensity parameter to retinex_edgemask to capture the minute details in a frame. Currently, raising the value of sigma just makes the edgemask expand but it doesn't enhance the details within said frame. 

Kind Regards

**Comment by kageru** [comment]
I’m not sure I understand. Do you mean a parameter to control the `scale` of tcanny (which allows it to detect finer edges, see [their docs](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-TCanny#usage)) or something more sophisticated? If it’s the latter, do you have anything specific in mind?

**Comment by nobananasforyou** [comment]
Yes, please. It would be nice to have the option to tweak the scale value of tcanny to detect finer edges. Also, I'm not sure but is it possible to use [https://github.com/Irrational-Encoding-Wizardry/vsmask](url) and try other masks because currently retinex is limited to tcanny.
