### ISSUE TITLE
Check for src bitdepth in _generate_descale_mask

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/kagefunc#9]
When generating a mask where the bitdepths of the `src` and `descaled`, it sometimes does not properly mask the credits. Tested with varying `thresholds` as well, and result is the same.

**Comment by kageru** [comment]
There is now a `debug` parameter in `mask_descale` that returns the mask. Bitdepth checking is also performed there. You should no longer have to call the private function.
